name: Auto Update Valuation
on:
  push:
  schedule:
    - cron: "0 1 * * *" # 每天凌晨1点自动更新
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install libs
        run: pip install requests pandas
      - name: Run script
        run: python get_valuation.py
      - name: Commit data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add data.json
          git commit -m "auto update valuation"
          git push
