name: Auto Update Valuation
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requests
        run: pip install requests -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: Run script
        run: python get_valuation.py
      - name: Push data
        run: |
          git config --global user.name "lxj9939"
          git config --global user.email "lxj9939@163.com"
          git add .
          git commit -m "update data" || true
          git push
